### ISSUE TITLE
request for the weights file

### ISSUE THREAD

**Issue by AaronDavis2020** [grasses/Constrained-CNN#1]
Hi, thanks for your amazing job! Could you share the model weights link?

**Comment by Yuhao-Sun** [comment]
Hi, thanks for your amazing job! Could you share the model weights link?

**Comment by grasses** [comment]
This repo doesn't include weights file.
`utils/model.py` contains the implement of paper "Constrained Convolutional Neural Networks: A New Approach Towards General Purpose Image Manipulation Detection", you should rewrite dataloader and train your dataset to obtain the weights file.
